### ISSUE TITLE
TextView intros in Lesson 5

### ISSUE THREAD

**Issue by mcrossman** [TalkbackTutorial/Application#108]
See #102. Higher priority than all other conversion tasks.

Due to a very prolific use of timers, this lesson needs conversion to prevent crashes. Most if not all transitions requiring timers are to blank pages which can hold TextViews instead of waiting for a TTS opportunity.

**Comment by mingxuan-fu** [comment]
Completed all activities and fragments, except where timers are used in the notification module and the talkback menu module, due to them needing to talk to the user while they are on a different page. A number of fragment layouts are redundant, but not removed to minimise code changes.
