### ISSUE TITLE
Talkback focus description on media controls

### ISSUE THREAD

**Issue by Andre-Pham** [TalkbackTutorial/Application#18]
The Talkback focus description on any of a media controller's components is less than ideal.
To reproduce:
1. Start a module that uses the media controller (e.g. Lesson 4 Module 1 Start and Stop Media)
2. Select the play button while Talkback is on.

This effect occurs on other parts of the media controller such as its body.

https://user-images.githubusercontent.com/60597159/169698341-b5e99a88-a82c-42bf-9cd1-3410e33a2763.mov

**Comment by llawll** [comment]
Seems like this is harder than just changing the description of the view in the XML file. Will need to look into it further. I'll probs will need to move this to the next sprint
