### ISSUE TITLE
Lesson 6 Doesn't Work

### ISSUE THREAD

**Issue by Andre-Pham** [TalkbackTutorial/Application#51]
The entirety of Lesson 6 doesn't work.
[Video](https://www.youtube.com/watch?v=hpGhcKYWZ-0&list=PLOawQ_LQymVG2g9UxI_Q90XK4EYbYdyyZ).

**Comment by sandy-du** [comment]
Fix Lesson 6 
https://github.com/TalkbackTutorial/Application/commit/1a2bfb329729b28bed169ef78a90177b08d3c274
