### ISSUE TITLE
Game mode - US3: Game mode has scoring system

### ISSUE THREAD

**Issue by mcrossman** [TalkbackTutorial/Application#63]
As a visually impaired user, I want the game mode to have a high score monitoring system, so that I can try to beat that high score every time.

**Comment by Andre-Pham** [comment]
We have a scoring system, but do we want to save the user's high score? It seems like a good idea, but reading out the player's high score during the introduction makes it even longer and even more tedious to get through every time. One possible option is that we just announce "new high-score" every time they beat their high score, and that's it.

**Comment by mcrossman** [comment]
> It seems like a good idea, but reading out the player's high score during the introduction makes it even longer and even more tedious to get through every time.

It would be more appropriate to approach this with a layout as opposed to TTS. This would allow extra info like high scores to be "set aside", allowing the user to skip over it during navigation if they don't care.

For example, you could have a results page that holds the run's score, the high score, and both a replay button and an exit button.

> One possible option is that we just announce "new high-score" every time they beat their high score, and that's it.

That's a valid option. However, how would you notify the user of their current high score if they don't beat it?
