### ISSUE TITLE
Remove Lesson 7

### ISSUE THREAD

**Issue by mcrossman** [TalkbackTutorial/Application#65]
Lesson 7 is no longer feasible.

**Comment by Andre-Pham** [comment]
This will require refactoring Lesson 8 into the "new" Lesson 7. You'll need to discuss with Team 3 on whether this should occur before or after the sprint merge, in order to avoid merge issues.

**Comment by mcrossman** [comment]
> This will require refactoring Lesson 8 into the "new" Lesson 7. You'll need to discuss with Team 3 on whether this should occur before or after the sprint merge, in order to avoid merge issues.

Better off doing this post-merge because of the `Lesson7` file conflict.

**Comment by llawll** [comment]
Removed lesson 7's files, will do the refactoring after the merge.
