### ISSUE TITLE
Back button in module list is unlabeled

### ISSUE THREAD

**Issue by mcrossman** [TalkbackTutorial/Application#81]
The back button at the top of the modules list page is read out as just "Button", which is unclear. It should state that it goes back to the main menu (Lessons page).

**Comment by Andre-Pham** [comment]
I'm not sure when/who fixed this, but it's providing feedback as of now (tested on commit 71acc35)

**Comment by mcrossman** [comment]
I fixed it in 1f86d5d72236143fd0e291841844db7d320d546c but forgot to close this issue at the time.
