### ISSUE TITLE
OpenVoiceCommandPart2Fragment is unused.

### ISSUE THREAD

**Issue by Andre-Pham** [TalkbackTutorial/Application#87]
OpenVoiceCommandPart2Fragment isn't used anywhere and crashes the application. This should either be referenced where it's needed or removed entirely if it's not being used.

If it is being kept, `val currentLesson : Lesson = LessonContainer.getAllLessons()[4]` needs to be changed to use `.getLesson`. This is a risk because if any lesson is added prior to this one, the code breaks.

**Comment by jaiclapp** [comment]
Missing lines of code were deleted during the merge. These lines have been added back in and OpenVoiceCommandPart2Fragment is now referenced again. The finish lesson component of OpenVoiceCommandPart2Fragment has been updated to fit a better design and is more inline with other fragments. Now up for review.

**Comment by jaiclapp** [comment]
This issue has been reviewed and completed.
