### ISSUE TITLE
Grammar and Clarity Review

### ISSUE THREAD

**Issue by Andre-Pham** [TalkbackTutorial/Application#88]
Every single string found in `strings.xml` needs to be reviewed for proper grammar and understandability, and if appropriate, made more concise.

**Comment by azho0003** [comment]
Certain strings are too long and may contain too many instructions at once. It may be beneficial to split these into multiple strings to improve clarity. Please review within the teams that created them.

> strings.xml

- Line 134 (explore by touch)
- Line 215 (open notifications)
