### ISSUE TITLE
Challenge outro message is inconsistent with most challenges

### ISSUE THREAD

**Issue by mcrossman** [TalkbackTutorial/Application#92]
The common message read on the completion of most challenges says:

> Find and select the back button to return to the main menu.

This only applies to Lesson 6's challenge, whereas the challenges for lessons 2 and 4 send you back automatically.

**Comment by Andre-Pham** [comment]
Resolved. Changed outro text in 1cfbfdf. Lesson 6 automatically returns to the main menu in f90be63.
